import { Node, mergeAttributes } from '@tiptap/core';
import { ReactNodeViewRenderer } from '@tiptap/react';
import { RoadmapFeaturesTableNodeView } from './roadmap-features-table-nodeview';

export interface RoadmapFeaturesTableOptions {
  HTMLAttributes: Record<string, any>;
}

declare module '@tiptap/core' {
  interface Commands<ReturnType> {
    roadmapFeaturesTable: {
      /**
       * Insert a roadmap features table
       */
      insertRoadmapFeaturesTable: (attributes?: { roadmapId?: string }) => ReturnType;
    };
  }
}

export const RoadmapFeaturesTable = Node.create<RoadmapFeaturesTableOptions>({
  name: 'roadmapFeaturesTable',

  addOptions() {
    return {
      HTMLAttributes: {},
    };
  },

  group: 'block',

  content: '',

  isolating: true,

  addAttributes() {
    return {
      roadmapId: {
        default: null,
        parseHTML: element => element.getAttribute('data-roadmap-id'),
        renderHTML: attributes => {
          if (!attributes.roadmapId) {
            return {};
          }
          return {
            'data-roadmap-id': attributes.roadmapId,
          };
        },
      },
      isAutoGenerated: {
        default: true,
        parseHTML: element => element.getAttribute('data-auto-generated') === 'true',
        renderHTML: attributes => ({
          'data-auto-generated': attributes.isAutoGenerated,
        }),
      },
    };
  },

  parseHTML() {
    return [
      {
        tag: 'div[data-type="roadmap-features-table"]',
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return [
      'div',
      mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
        'data-type': 'roadmap-features-table',
      }),
    ];
  },

  addNodeView() {
    return ReactNodeViewRenderer(RoadmapFeaturesTableNodeView);
  },

  addCommands() {
    return {
      insertRoadmapFeaturesTable:
        (attributes = {}) =>
        ({ commands }) => {
          return commands.insertContent({
            type: this.name,
            attrs: attributes,
          });
        },
    };
  },
});