import { Node } from '@tiptap/core';
import { ReactNodeViewRenderer } from '@tiptap/react';
import RequirementsTableNodeView from './requirements-table-nodeview';

export const RequirementsTableExtension = Node.create({
  name: 'requirementsTable',

  group: 'block',

  isolating: true,

  defining: true,

  draggable: false,

  content: '',

  addAttributes() {
    return {
      featureId: {
        default: null,
      },
      isAutoGenerated: {
        default: false,
      },
    };
  },

  parseHTML() {
    return [
      {
        tag: 'div[data-requirements-table]',
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return ['div', { 'data-requirements-table': '', ...HTMLAttributes }];
  },

  addNodeView() {
    return ReactNodeViewRenderer(RequirementsTableNodeView);
  },

  addCommands() {
    return {
      insertRequirementsTable:
        (attrs?: { featureId?: string }) =>
        ({ commands }) => {
          return commands.insertContent({
            type: this.name,
            attrs: {
              featureId: attrs?.featureId || null,
              isAutoGenerated: false,
            },
          });
        },
    };
  },
});