import React from 'react';
import { NodeViewWrapper, NodeViewProps } from '@tiptap/react';
import { RequirementsPagesTable } from './requirements-pages-table';

interface RequirementsTableAttrs {
  featureId: string | null;
  isAutoGenerated: boolean;
}

export default function RequirementsTableNodeView({ node }: NodeViewProps) {
  const attrs = node.attrs as RequirementsTableAttrs;
  const featureId = attrs.featureId;

  if (!featureId) {
    return (
      <NodeViewWrapper className="requirements-table-wrapper my-4">
        <div className="rounded-lg border bg-card p-4 text-muted-foreground">
          <p>Requirements table requires a feature context</p>
        </div>
      </NodeViewWrapper>
    );
  }

  return (
    <NodeViewWrapper className="requirements-table-node">
      {/* Container gets px-6 from unified editor, add top padding for spacing */}
      <div className="pt-6 pb-0">
        <h3 className="text-lg font-semibold mb-4 text-white">Requirements</h3>
        {/* Requirements table with DataTable styling */}
        <div className="requirements-data-table">
          <RequirementsPagesTable 
            featureId={featureId}
            isEditable={true}
          />
        </div>
      </div>
      
      {/* Clean layout styling to match roadmap table */}
      <style jsx>{`
        /* Node wrapper layout */
        .requirements-table-node {
          margin: 0 !important;
          display: block !important;
        }
      `}</style>
    </NodeViewWrapper>
  );
}